#!/usr/bin/env python3
"""Generate the relation/v0.1 conformance vectors (run ONCE, fixtures are committed bytes).

Provenance: relation/v0.1 lineage profile (3.3.0, EXPERIMENTAL). The five skeleton vectors
carry crossFormatId xfmt-c0/t1..t4 per the No Silent Landing shared-vector convention
(PB-LINEAGE-XFMT-SYNC-20260715 §1); superset vectors (cycle, depth, unauthorized-signer,
declared-unresolved, retracts-then-use, malformed-digest F6, one per relation) carry none.
All signing keys are FRESH THROWAWAY TEST KEYS generated at build time and never stored —
every receipt verifies via its embedded/derived public key material recorded in pub.b64.

Regeneration changes bytes (fresh keys) — treat like any fixture regeneration: rerun this
script, re-review the diff, recommit. Never hand-edit generated fixtures.
"""
from __future__ import annotations

import base64
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "src"))

from proofbundle import anchors, dsse  # noqa: E402
from proofbundle.decision import emit_decision_receipt  # noqa: E402
from proofbundle.emit import generate_signer  # noqa: E402
from proofbundle.outcome import emit_outcome_receipt  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
EXAMPLES = HERE.parents[1] / "examples"

BASE_PRED = json.loads((EXAMPLES / "decision_receipt_deny.json").read_text(encoding="utf-8"))

# Minimal valid action-outcome/v0.1 predicate (WP-B outcome-path mirror vectors). The relationships
# field is injected per vector; all digests are valid throwaway sha256 values.
_D = "1" * 64
OUTCOME_BASE = {
    "schemaVersion": "0.1.0",
    "outcomeId": "urn:uuid:11111111-1111-1111-1111-111111111111",
    "decisionRef": {"sha256": _D},
    "executor": {"id": "executor://example/runner"},
    "requestedActionDigest": {"sha256": _D},
    "effectDigest": {"sha256": _D},
    "status": "executed",
    "performedAt": "2026-07-16T00:00:00Z",
    "policyPurpose": "outcome",
}


def edge(target_hex: str, relation: str = "supersedes", **extra) -> dict:
    e = {"relation": relation,
         "targetReceiptDigest": {"digestAlgorithm": "jcs-sha256-v1", "digest": target_hex}}
    e.update(extra)
    return e


def content_root_hex(env: dict) -> str:
    return anchors.statement_content_root(dsse.load_payload(env)).hex()


def subject_hex(env: dict) -> str:
    """The subject digest (subject[0].digest.sha256) of an emitted receipt — the ground truth the
    edge's optional targetSubjectDigest is gegengeprueft against (WP-A2/O2)."""
    stmt = json.loads(dsse.load_payload(env).decode("utf-8"))
    return stmt["subject"][0]["digest"]["sha256"]


def pub_of(signer) -> str:
    return base64.b64encode(signer.public_key().public_bytes_raw()).decode()


def emit(pred_patch: dict | None, signer) -> dict:
    pred = json.loads(json.dumps(BASE_PRED))
    if pred_patch:
        pred.update(pred_patch)
    return emit_decision_receipt(pred, signer, strict=True)


def emit_outcome(pred_patch: dict | None, signer) -> dict:
    pred = json.loads(json.dumps(OUTCOME_BASE))
    if pred_patch:
        pred.update(pred_patch)
    return emit_outcome_receipt(pred, signer, strict=True)


def write_case(name: str, files: dict, case: dict) -> None:
    d = HERE / name
    d.mkdir(parents=True, exist_ok=True)
    for fname, obj in files.items():
        if isinstance(obj, (dict, list)):
            (d / fname).write_text(json.dumps(obj, indent=1, ensure_ascii=False) + "\n",
                                   encoding="utf-8")
        else:
            (d / fname).write_text(str(obj), encoding="utf-8")
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False) + "\n",
                                 encoding="utf-8")
    print("wrote", name)


def base_case(case_id: str, expected: dict, rationale: str, *, related=None, policy=None,
              cross_format_id: str | None = None, related_pubs=None, kind: str = "decision_relation",
              attribution: str | None = None) -> dict:
    c = {
        "caseId": case_id,
        "kind": kind,
        "input": "receipt.json",
        "pub": "pub.b64",
        "expected": expected,
        "attribution": attribution or "b7n0de / relation-v0.1 corpus generator "
                       "(conformance/relation/generate_vectors.py, 2026-07-16)",
        "specRefs": ["docs/predicates/relation.md", "docs/design/RELATION_V01_DESIGN.md"],
        "rationale": rationale,
        "testKeys": "fresh throwaway keys, generated by conformance/relation/generate_vectors.py",
    }
    if related:
        c["related"] = related
    if related_pubs is not None:
        c["relatedPubs"] = related_pubs
    if policy:
        c["policy"] = policy
    if cross_format_id:
        c["crossFormatId"] = cross_format_id
    return c


V02 = "proofbundle/trust-policy/v0.2"


def main() -> None:
    signer = generate_signer()          # der Haupt-Aussteller (same-key-Vertrag)
    stranger = generate_signer()        # fremder Signer (unauthorized-signer-Vektor)
    pub_b64 = base64.b64encode(signer.public_key().public_bytes_raw()).decode()

    # Vorgaenger B (gemeinsame Basis vieler Vektoren)
    b_env = emit({"decisionId": "d-predecessor"}, signer)
    b_root = content_root_hex(b_env)

    # 1) valid-baseline (xfmt-c0): keine relationships -> exit 0, lineage null/NOT_EVALUATED
    a0 = emit({"decisionId": "d-baseline"}, signer)
    write_case("valid-baseline",
               {"receipt.json": a0, "pub.b64": pub_b64},
               base_case("relation-valid-baseline",
                         {"exitCode": 0, "lineage": None},
                         "Compatibility floor: a receipt without the profile verifies exactly as "
                         "before; lineage stays NOT_EVALUATED (reported null).",
                         cross_format_id="xfmt-c0"))

    # 2) silent-landing (xfmt-t1, benannter Kernvektor): alte Identitaet, neue Bytes,
    #    KEINE erklaerte Relation -> Krypto-FAIL exit 1.
    a1 = emit({"decisionId": "d-baseline"}, signer)
    body = json.loads(base64.b64decode(a1["payload"]))
    body["predicate"]["decision"]["humanReadableSummary"] = "silently swapped content"
    a1_tampered = dict(a1, payload=base64.b64encode(
        json.dumps(body, separators=(",", ":")).encode()).decode())
    write_case("silent-landing",
               {"receipt.json": a1_tampered, "pub.b64": pub_b64},
               base_case("relation-silent-landing",
                         {"exitCode": 1},
                         "The core must-fail: new bytes presented under the old receipt's "
                         "identity with NO declared relation — indistinguishable from tampering, "
                         "and it FAILS (crypto, exit 1). Legitimate change becomes visible; "
                         "impersonation does not.",
                         cross_format_id="xfmt-t1"))

    # 3) declared-supersedes-verified (xfmt-t2)
    a2 = emit({"decisionId": "d-successor",
               "relationships": [edge(b_root, relation="supersedes",
                                      reasonCode="correction",
                                      declaredAt="2026-07-16T00:00:00Z")]}, signer)
    write_case("declared-supersedes-verified",
               {"receipt.json": a2, "pub.b64": pub_b64, "related_b.json": b_env},
               base_case("relation-declared-supersedes-verified",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "Declared supersession with the predecessor attached and standalone-"
                         "verified: lineage VERIFIED. Proves the declared derivation, never that "
                         "the successor is better or true (claim boundary).",
                         related=["related_b.json"], cross_format_id="xfmt-t2"))

    # 4) digest-mismatch (xfmt-t3): Kante zeigt auf FALSCHEN Digest; Policy verlangt Aufloesung
    wrong = "0" * 63 + "1"
    a3 = emit({"decisionId": "d-mismatch",
               "relationships": [edge(wrong, relation="supersedes")]}, signer)
    pol3 = {"schema": "proofbundle/trust-policy/v0.2", "policy_id": "relation-t3",
            "relations": {"require_relation_resolution": ["supersedes"]}}
    write_case("digest-mismatch",
               {"receipt.json": a3, "pub.b64": pub_b64, "related_b.json": b_env,
                "policy.json": pol3},
               base_case("relation-digest-mismatch",
                         {"exitCode": 3, "lineage": "DECLARED_UNRESOLVED",
                          "errorContains": "LINEAGE_REQUIREMENT_FAILED"},
                         "Parent digest mismatch (shared T3): the edge names a digest the attached "
                         "predecessor does NOT have, so the required relation cannot resolve — the "
                         "policy turns that into a hard FAIL (exit 3, LINEAGE_REQUIREMENT_FAILED). "
                         "The mismatch manifests as failure-to-resolve because attached targets are "
                         "keyed by their COMPUTED content root (a lying edge never finds a target).",
                         related=["related_b.json"], policy="policy.json",
                         cross_format_id="xfmt-t3"))

    # 5) renews-vector (xfmt-t4)
    a4 = emit({"decisionId": "d-renewal",
               "relationships": [edge(b_root, relation="renews")]}, signer)
    write_case("renews-vector",
               {"receipt.json": a4, "pub.b64": pub_b64, "related_b.json": b_env},
               base_case("relation-renews-vector",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "Evidence renewal (shared T4): renews = same evidence, new anchors — "
                         "explicitly disjoint from supersedes; the original's identity and age stay "
                         "visible (the predecessor stays attached and valid for its bytes).",
                         related=["related_b.json"], cross_format_id="xfmt-t4"))

    # 6-10) je Relation ein Vektor (supersedes via t2, renews via t4 abgedeckt)
    for rel in ("revises", "corrects", "retracts", "derivedFrom", "amends"):
        env = emit({"decisionId": f"d-{rel.lower()}",
                    "relationships": [edge(b_root, relation=rel)]}, signer)
        write_case(f"relation-{rel.lower()}",
                   {"receipt.json": env, "pub.b64": pub_b64, "related_b.json": b_env},
                   base_case(f"relation-edge-{rel.lower()}",
                             {"exitCode": 0, "lineage": "VERIFIED"},
                             f"One vector per relation: a {rel} edge onto the attached, verified "
                             "predecessor resolves to lineage VERIFIED with the relation's own "
                             "semantics (mapping table in the SPEC chapter).",
                             related=["related_b.json"]))

    # 10) declared-unresolved: Kante ohne beigelegtes Ziel -> kein Fehler, kein PASS-Upgrade
    a10 = emit({"decisionId": "d-unresolved",
                "relationships": [edge(b_root, relation="supersedes")]}, signer)
    write_case("declared-unresolved",
               {"receipt.json": a10, "pub.b64": pub_b64},
               base_case("relation-declared-unresolved",
                         {"exitCode": 0, "lineage": "DECLARED_UNRESOLVED"},
                         "Edge present, target not attached: explicitly NOT an error, but never "
                         "more than declared — no PASS upgrade (lattice monotonicity)."))

    # 11) depth-exceeded: gerade Kette laenger als MAX_CHAIN_DEPTH=32, rueckwaerts gebaut.
    #    (Ein ECHTER Hash-Zyklus ist mit Content-Root-Adressierung konstruktiv UNMOEGLICH —
    #    der Root eines Belegs enthaelt seine Kanten, eine Rueckkante brauchte den finalen
    #    Root des Nachfolgers: zirkulaere Hash-Abhaengigkeit. Der Cycle-Guard bleibt als
    #    Defense-in-Depth gegen manipulierte related-Maps/Verifier-Bugs UNIT-getestet;
    #    das fixture-realisierbare Tiefen-Limit wird hier end-to-end exerziert.)
    chain = [emit({"decisionId": "d-chain-001"}, signer)]
    for i in range(2, 35):
        prev_root = content_root_hex(chain[-1])
        chain.append(emit({"decisionId": f"d-chain-{i:03d}",
                           "relationships": [edge(prev_root, relation="derivedFrom")]}, signer))
    a11 = chain[-1]                      # R34 = Pruefobjekt
    attached = chain[:-1]                # R1..R33 beigelegt
    files11 = {"receipt.json": a11, "pub.b64": pub_b64}
    rel_names = []
    for i, env in enumerate(attached, start=1):
        fname = f"related_{i:03d}.json"
        files11[fname] = env
        rel_names.append(fname)
    write_case("depth-exceeded", files11,
               base_case("relation-depth-exceeded",
                         {"exitCode": 2, "lineage": "FAIL",
                          "errorContains": "relation:depth_exceeded"},
                         "A straight attached ancestry deeper than the hard cap (32) FAILS with a "
                         "stable code — a resource bound, honestly reported. Real hash CYCLES are "
                         "impossible to construct under content-root addressing (a receipt's root "
                         "contains its own edges); the cycle guard stays unit-tested defense-in-depth.",
                         related=rel_names))

    # 12) unauthorized-signer: Vorgaenger von FREMDEM Key -> attached-but-unverified -> FAIL exit 2
    b_foreign = emit({"decisionId": "d-foreign"}, stranger)
    b_foreign_root = content_root_hex(b_foreign)
    a12 = emit({"decisionId": "d-succ-foreign",
                "relationships": [edge(b_foreign_root, relation="supersedes")]}, signer)
    write_case("unauthorized-signer",
               {"receipt.json": a12, "pub.b64": pub_b64, "related_b.json": b_foreign},
               base_case("relation-unauthorized-signer",
                         {"exitCode": 2, "lineage": "FAIL",
                          "errorContains": "relation:target_verification_failed"},
                         "The attached predecessor is signed by a FOREIGN key (same-key CLI "
                         "contract): attached-but-unverified is present-and-wrong and FAILS hard — "
                         "unlike an absent target, which stays declared-only.",
                         related=["related_b.json"]))

    # 13) malformed-digest (F6, Annex — EIGENER Never-Raise-Vektor, getrennt vom Mismatch).
    #    Der ehrliche Emitter WEIGERT sich, das zu emittieren (fail-closed, gut so) — der Fixture
    #    wird deshalb bewusst auf DSSE-Ebene gecraftet: valide Signatur ueber ein Statement mit
    #    Nicht-Hex-Sentinel im Edge-Digest. Genau das prueft der Vektor: der VERIFIER muss FAIL
    #    melden, nie werfen.
    _ok13 = emit({"decisionId": "d-malformed",
                  "relationships": [edge(b_root, relation="supersedes")]}, signer)
    _body13 = json.loads(base64.b64decode(_ok13["payload"]))
    _body13["predicate"]["relationships"][0]["targetReceiptDigest"]["digest"] = (
        "INTENTIONALLY_WRONG_NATIVE_DIGEST")
    try:
        import rfc8785  # noqa: PLC0415
        _bytes13 = rfc8785.dumps(_body13)
        if isinstance(_bytes13, str):
            _bytes13 = _bytes13.encode()
    except Exception:
        _bytes13 = json.dumps(_body13, separators=(",", ":"), sort_keys=True).encode()
    a13 = dsse.sign_envelope(_bytes13, signer,
                             payload_type="application/vnd.in-toto+json")
    write_case("malformed-digest",
               {"receipt.json": a13, "pub.b64": pub_b64},
               base_case("relation-malformed-digest",
                         {"exitCode": 2, "lineage": "FAIL",
                          "errorContains": "relation:malformed"},
                         "F6 (V0.1A annex): a NON-HEX digest sentinel is its own never-raise vector, "
                         "deliberately separate from digest-MISMATCH — the parser must report FAIL, "
                         "never throw. Exercises the malformed path end-to-end through the CLI."))

    # 14) retracts-then-use: beigelegter verifizierter Beleg RETRACTS das Pruefobjekt + Policy
    a14 = emit({"decisionId": "d-in-use"}, signer)
    a14_root = content_root_hex(a14)
    retractor = emit({"decisionId": "d-retractor",
                      "relationships": [edge(a14_root, relation="retracts",
                                             reasonCode="withdrawal")]}, signer)
    pol14 = {"schema": "proofbundle/trust-policy/v0.2", "policy_id": "relation-retracts",
             "relations": {"reject_superseded": True}}
    write_case("retracts-then-use",
               {"receipt.json": a14, "pub.b64": pub_b64, "related_r.json": retractor,
                "policy.json": pol14},
               base_case("relation-retracts-then-use",
                         {"exitCode": 3,
                          "errorContains": "LINEAGE_REQUIREMENT_FAILED"},
                         "Using a receipt that an attached, verified receipt has RETRACTED: the "
                         "retraction never breaks the target's crypto (it stays valid for its "
                         "bytes), but reject_superseded turns continued automated use into a "
                         "policy blocker (exit 3).",
                         related=["related_r.json"], policy="policy.json"))

    # ══ 3.4.0 vectors: WP-A relation_signer · WP-A2 require_relation_target + targetSubjectDigest ══
    other = generate_signer()           # dritter Key (pinned-Menge-Nichtmitglied)
    x_pub, y_pub, o_pub = pub_of(signer), pub_of(stranger), pub_of(other)

    # (a) cross-issuer-verified: successor (ring X) supersedes a predecessor of a FOREIGN ring (Y);
    #     the successor ring is in the pinned relation_signer set; the target verifies under ITS own
    #     key (--related-pub). → lineage VERIFIED + policy PASS. The cross-issuer chain the same-key
    #     CLI contract could NOT express before 3.4.0.
    fb = emit({"decisionId": "d-foreign-pred"}, stranger)
    fb_root = content_root_hex(fb)
    xa = emit({"decisionId": "d-x-successor",
               "relationships": [edge(fb_root, relation="supersedes")]}, signer)
    pol_a = {"schema": V02, "policy_id": "relsig-cross-verified",
             "relations": {"relation_signer": {"supersedes": {"mode": "pinned", "keys": [x_pub]}}}}
    write_case("relation-signer-cross-issuer-verified",
               {"receipt.json": xa, "pub.b64": x_pub, "related_b.json": fb, "policy.json": pol_a},
               base_case("relation-signer-cross-issuer-verified",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "WP-A: a successor of ring X supersedes a predecessor of a FOREIGN ring Y; "
                         "the predecessor is attached and verifies under its own key (--related-pub), "
                         "and X is a member of the pinned relation_signer set. Cross-issuer lineage "
                         "VERIFIED + policy PASS. Set membership under the verifier's pins, never a "
                         "proof of authority.",
                         related=["related_b.json"], related_pubs=[y_pub], policy="policy.json"))

    # (b) cross-issuer-unauthorized: same chain, but the pinned set does NOT contain the successor
    #     ring → RELATION_SIGNER_UNAUTHORIZED, exit 3. Crypto stays valid; falls ONLY in policy.
    pol_b = {"schema": V02, "policy_id": "relsig-cross-unauth",
             "relations": {"relation_signer": {"supersedes": {"mode": "pinned", "keys": [o_pub]}}}}
    write_case("relation-signer-cross-issuer-unauthorized",
               {"receipt.json": xa, "pub.b64": x_pub, "related_b.json": fb, "policy.json": pol_b},
               base_case("relation-signer-cross-issuer-unauthorized",
                         {"exitCode": 3, "lineage": "VERIFIED",
                          "errorContains": "RELATION_SIGNER_UNAUTHORIZED"},
                         "WP-A: the successor ring X is NOT in the pinned relation_signer set (only a "
                         "third key O is) → RELATION_SIGNER_UNAUTHORIZED, exit 3. The successor is "
                         "still crypto-valid and the target still resolves (lineage VERIFIED) — the "
                         "block is EXCLUSIVELY in the policy verdict (lattice monotonicity).",
                         related=["related_b.json"], related_pubs=[y_pub], policy="policy.json"))

    # (c) same-key-explicit: relation_signer {mode:same-key} with the target verified under the SAME
    #     key as the successor → PASS (the explicit form of today's default).
    sk_b = emit({"decisionId": "d-samekey-pred"}, signer)
    sk_root = content_root_hex(sk_b)
    sk_a = emit({"decisionId": "d-samekey-succ",
                 "relationships": [edge(sk_root, relation="supersedes")]}, signer)
    pol_c = {"schema": V02, "policy_id": "relsig-samekey",
             "relations": {"relation_signer": {"supersedes": {"mode": "same-key"}}}}
    write_case("relation-signer-same-key-explicit",
               {"receipt.json": sk_a, "pub.b64": x_pub, "related_b.json": sk_b, "policy.json": pol_c},
               base_case("relation-signer-same-key-explicit",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "WP-A: relation_signer {mode:same-key} — the successor issuer key equals the "
                         "key the target verifies under (both X). The explicit form of the pre-3.4.0 "
                         "default; PASS.",
                         related=["related_b.json"], related_pubs=[x_pub], policy="policy.json"))

    # (d) verified_under-not-claim: under {mode:same-key}, a target that verifies under a DIFFERENT
    #     key (Y) than the successor (X) FAILs — the check binds the ACTUAL verification key, never a
    #     claim. RELATION_SIGNER_UNAUTHORIZED, exit 3.
    write_case("relation-signer-verified-under-not-claim",
               {"receipt.json": xa, "pub.b64": x_pub, "related_b.json": fb, "policy.json": pol_c},
               base_case("relation-signer-verified-under-not-claim",
                         {"exitCode": 3, "lineage": "VERIFIED",
                          "errorContains": "RELATION_SIGNER_UNAUTHORIZED"},
                         "WP-A: under {mode:same-key} the target verifies under ring Y but the "
                         "successor is ring X → the same-key rule FAILs (exit 3). Proof the check "
                         "binds verified_under (the REAL verification key), never a declared/claimed "
                         "key — a lying edge cannot satisfy it.",
                         related=["related_b.json"], related_pubs=[y_pub], policy="policy.json"))

    # (f) T3_DECOY_PARENT_RESOLUTION (xfmt-t3-decoy, Loek F1, EMPIRICALLY reproduced): R0 (the RIGHT
    #     parent) AND a valid decoy RX both attached+verified; the child supersedes -> RX. Under
    #     require_relation_target pinning R0 the edge resolves to a VALID but WRONG parent → hard FAIL
    #     (RELATION_TARGET_MISMATCH, exit 3). Before 3.4.0 this passed (exit 0, VERIFIED).
    r0 = emit({"decisionId": "d-r0-right-parent"}, signer)
    r0_root, r0_subj = content_root_hex(r0), subject_hex(r0)
    rx = emit({"decisionId": "d-rx-decoy-parent"}, signer)
    rx_root = content_root_hex(rx)
    child_rx = emit({"decisionId": "d-child-supersedes-decoy",
                     "relationships": [edge(rx_root, relation="supersedes")]}, signer)
    pol_target_r0 = {"schema": V02, "policy_id": "reltgt-r0",
                     "relations": {"require_relation_target": {"supersedes": [r0_root]}}}
    loek = ("Loek Verdonk / No Silent Landing — adversarial review "
            "PROOFBUNDLE_3_3_0_ADVERSARIAL_REVIEW_V0.zip finding F1 (decoy parent), empirically "
            "reproduced 2026-07-16; b7n0de 3.4.0 fix")
    write_case("decoy-parent-target-mismatch",
               {"receipt.json": child_rx, "pub.b64": x_pub, "related_r0.json": r0,
                "related_rx.json": rx, "policy.json": pol_target_r0},
               base_case("relation-decoy-parent-target-mismatch",
                         {"exitCode": 3, "lineage": "VERIFIED",
                          "errorContains": "RELATION_TARGET_MISMATCH"},
                         "WP-A2 KERNFUND (F1): both R0 (right parent) and a valid decoy RX are "
                         "attached; the child supersedes->RX. require_relation_resolution alone would "
                         "PASS (RX resolves). require_relation_target pinning R0 rejects the "
                         "valid-but-WRONG parent — RELATION_TARGET_MISMATCH, exit 3. Crypto untouched "
                         "(lineage VERIFIED); the block is exclusively in the policy verdict.",
                         related=["related_r0.json", "related_rx.json"],
                         related_pubs=[x_pub, x_pub], policy="policy.json",
                         cross_format_id="xfmt-t3-decoy", attribution=loek))

    # (f-pass) GEGENPROBE: same shape, child supersedes -> R0 (the pinned parent) → PASS.
    child_r0 = emit({"decisionId": "d-child-supersedes-right",
                     "relationships": [edge(r0_root, relation="supersedes")]}, signer)
    write_case("decoy-parent-correct-pass",
               {"receipt.json": child_r0, "pub.b64": x_pub, "related_r0.json": r0,
                "related_rx.json": rx, "policy.json": pol_target_r0},
               base_case("relation-decoy-parent-correct-pass",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "WP-A2 gegenprobe (must-pass): identical setup, but the child supersedes->R0 "
                         "(the pinned parent) → PASS. Proves the target-pin admits the RIGHT parent "
                         "and rejects only the wrong one.",
                         related=["related_r0.json", "related_rx.json"],
                         related_pubs=[x_pub, x_pub], policy="policy.json", attribution=loek))

    # (f-old) NO-PIN old behavior: same decoy child, only require_relation_resolution → exit 0,
    #     VERIFIED — documents the CLOSED gap, not a silent change of behavior.
    pol_res_only = {"schema": V02, "policy_id": "relres-only",
                    "relations": {"require_relation_resolution": ["supersedes"]}}
    write_case("decoy-parent-no-pin-old-behavior",
               {"receipt.json": child_rx, "pub.b64": x_pub, "related_r0.json": r0,
                "related_rx.json": rx, "policy.json": pol_res_only},
               base_case("relation-decoy-parent-no-pin-old-behavior",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "WP-A2 documentation: WITHOUT require_relation_target (only "
                         "require_relation_resolution) the decoy child->RX resolves and PASSes — the "
                         "exact pre-3.4.0 behavior, recorded so the closed gap is visible, never "
                         "silently changed.",
                         related=["related_r0.json", "related_rx.json"],
                         related_pubs=[x_pub, x_pub], policy="policy.json", attribution=loek))

    # (g) T3_DECOY_ON_ACCEPT_PATH (O1): ONLY the decoy RX attached (the previously-'good' accepted T2
    #     supersedes that resolves VERIFIED); require_relation_target pins R0 (not even attached) →
    #     FAIL. Proves the pin is NOT T3-specific — it guards EVERY supersedes edge, accept path too.
    write_case("decoy-accept-path",
               {"receipt.json": child_rx, "pub.b64": x_pub, "related_rx.json": rx,
                "policy.json": pol_target_r0},
               base_case("relation-decoy-on-accept-path",
                         {"exitCode": 3, "lineage": "VERIFIED",
                          "errorContains": "RELATION_TARGET_MISMATCH"},
                         "WP-A2 O1: the accepted T2 path — child supersedes->RX resolves VERIFIED "
                         "(RX attached, R0 not) — STILL FAILs under require_relation_target pinning "
                         "R0. There is no code path on which a supersedes edge passes without the "
                         "target check once the pin is set.",
                         related=["related_rx.json"], related_pubs=[x_pub],
                         policy="policy.json", attribution=loek))

    # (h) RELATION_TARGET_SUBJECT_MISMATCH (O2): correct targetReceiptDigest (R0) but a WRONG
    #     targetSubjectDigest → lineage FAIL as soon as the field is present. Exit 2.
    wrong_subj = "f" * 64
    child_subj_bad = emit({"decisionId": "d-child-subj-mismatch",
                           "relationships": [edge(r0_root, relation="supersedes",
                                                  targetSubjectDigest={"digestAlgorithm": "jcs-sha256-v1",
                                                                       "digest": wrong_subj})]}, signer)
    write_case("target-subject-mismatch",
               {"receipt.json": child_subj_bad, "pub.b64": x_pub, "related_r0.json": r0},
               base_case("relation-target-subject-mismatch",
                         {"exitCode": 2, "lineage": "FAIL",
                          "errorContains": "RELATION_TARGET_SUBJECT_MISMATCH"},
                         "WP-A2 O2: the edge names the correct targetReceiptDigest (R0) but declares a "
                         "WRONG targetSubjectDigest. The previously dormant field is now binding when "
                         "present: it is gegengeprueft against the resolved target's real subject → "
                         "lineage FAIL, exit 2.",
                         related=["related_r0.json"], related_pubs=[x_pub], attribution=loek))

    # (h-pass) GEGENPROBE: correct targetSubjectDigest (= R0's real subject) → VERIFIED, exit 0.
    child_subj_ok = emit({"decisionId": "d-child-subj-ok",
                          "relationships": [edge(r0_root, relation="supersedes",
                                                 targetSubjectDigest={"digestAlgorithm": "jcs-sha256-v1",
                                                                      "digest": r0_subj})]}, signer)
    write_case("target-subject-correct-pass",
               {"receipt.json": child_subj_ok, "pub.b64": x_pub, "related_r0.json": r0},
               base_case("relation-target-subject-correct-pass",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "WP-A2 O2 gegenprobe: the SAME edge with the CORRECT targetSubjectDigest (the "
                         "resolved target's real subject digest) → VERIFIED, exit 0. Proves the "
                         "gegenpruefung admits a truthful subject claim.",
                         related=["related_r0.json"], related_pubs=[x_pub], attribution=loek))

    # (i) T1_CANONICAL_INVALID_SIGNATURE (F2): a JCS-CANONICAL tamper (an evidenceRefs digest swapped
    #     for another valid value, re-canonicalized) with the OLD signature kept → FAILs on the
    #     SIGNATURE ALONE (exit 1), no second canonicality fail. Faithful constructed equivalent of
    #     Loek's T1_CLEAN_CANONICAL_INVALID_SIGNATURE_PRESENTATION (the exact bytes live in the
    #     external review bundle and are NOT embedded here — attribution below).
    t1_ok = emit({"decisionId": "d-t1-canonical"}, signer)
    _t1_body = json.loads(base64.b64decode(t1_ok["payload"]))
    _refs = _t1_body["predicate"].get("evidenceRefs") or []
    if _refs and isinstance(_refs[0], dict) and isinstance(_refs[0].get("digest"), dict):
        _refs[0]["digest"]["sha256"] = "a" * 64          # another VALID digest — canonical, wrong sig
    else:                                                # fallback: perturb the human summary
        _t1_body["predicate"]["decision"]["humanReadableSummary"] = "canonical tamper (F2)"
    try:
        import rfc8785  # noqa: PLC0415
        _t1_bytes = rfc8785.dumps(_t1_body)
        if isinstance(_t1_bytes, str):
            _t1_bytes = _t1_bytes.encode()
    except Exception:
        _t1_bytes = json.dumps(_t1_body, separators=(",", ":"), sort_keys=True).encode()
    t1 = dict(t1_ok, payload=base64.b64encode(_t1_bytes).decode())  # keep the ORIGINAL signature
    write_case("t1-canonical-invalid-signature",
               {"receipt.json": t1, "pub.b64": x_pub},
               base_case("relation-t1-canonical-invalid-signature",
                         {"exitCode": 1},
                         "F2 (Loek): a JCS-CANONICAL tamper (a valid digest swapped for another valid "
                         "digest, re-canonicalized) with the ORIGINAL signature kept → FAILs on the "
                         "SIGNATURE alone (exit 1), never a second canonicality error. Faithful "
                         "constructed equivalent of Loek's byte artifact (exact bytes in the external "
                         "review bundle, not embedded).",
                         attribution=loek))

    # ══ WP-B: outcome-path mirror (kind outcome_relation) — the relations gate on the outcome verb ══
    # (e) five-skeleton mirror (internal names, NO crossFormatId — the shared skeleton is decision-side)
    o_pred = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-11111111000e"}, signer)
    write_case("outcome-valid-baseline",
               {"receipt.json": o_pred, "pub.b64": x_pub},
               base_case("outcome-relation-valid-baseline",
                         {"exitCode": 0, "lineage": None},
                         "WP-B (e/c0): an outcome receipt without the profile verifies exactly as "
                         "before; lineage NOT_EVALUATED (null).", kind="outcome_relation"))

    o_pred_body = json.loads(base64.b64decode(o_pred["payload"]))
    o_pred_body["predicate"]["outcomeId"] = "urn:uuid:tampered"
    o_tampered = dict(o_pred, payload=base64.b64encode(
        json.dumps(o_pred_body, separators=(",", ":")).encode()).decode())
    write_case("outcome-silent-landing",
               {"receipt.json": o_tampered, "pub.b64": x_pub},
               base_case("outcome-relation-silent-landing",
                         {"exitCode": 1},
                         "WP-B (e/t1): new outcome bytes under the old identity with NO declared "
                         "relation → crypto FAIL, exit 1.", kind="outcome_relation"))

    o_pred_b = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-1111110000b0"}, signer)
    o_b_root = content_root_hex(o_pred_b)
    o_succ = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-1111110000b1",
                           "relationships": [edge(o_b_root, relation="supersedes")]}, signer)
    write_case("outcome-declared-supersedes-verified",
               {"receipt.json": o_succ, "pub.b64": x_pub, "related_b.json": o_pred_b},
               base_case("outcome-relation-declared-supersedes-verified",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "WP-B (e/t2): declared supersession with the predecessor attached and "
                         "standalone-verified on the OUTCOME path: lineage VERIFIED.",
                         related=["related_b.json"], kind="outcome_relation"))

    o_wrong = "0" * 63 + "2"
    o_mismatch = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-1111110000t3",
                               "relationships": [edge(o_wrong, relation="supersedes")]}, signer)
    write_case("outcome-digest-mismatch",
               {"receipt.json": o_mismatch, "pub.b64": x_pub, "related_b.json": o_pred_b,
                "policy.json": pol_res_only},
               base_case("outcome-relation-digest-mismatch",
                         {"exitCode": 3, "lineage": "DECLARED_UNRESOLVED",
                          "errorContains": "LINEAGE_REQUIREMENT_FAILED"},
                         "WP-B (e/t3): the outcome-path relations gate — a required supersedes edge "
                         "that cannot resolve (the named digest matches no attached target) FAILs "
                         "policy, exit 3. Identical gate + code as the decision path.",
                         related=["related_b.json"], policy="policy.json", kind="outcome_relation"))

    o_renew = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-1111110000t4",
                            "relationships": [edge(o_b_root, relation="renews")]}, signer)
    write_case("outcome-renews",
               {"receipt.json": o_renew, "pub.b64": x_pub, "related_b.json": o_pred_b},
               base_case("outcome-relation-renews",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "WP-B (e/t4): renews on the OUTCOME path — same evidence, new anchors; the "
                         "predecessor stays attached and valid.",
                         related=["related_b.json"], kind="outcome_relation"))

    # WP-B relation_signer + require_relation_target ON the outcome path (exit-3 mirror of decision).
    o_fb = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-11111100f000"}, stranger)
    o_fb_root = content_root_hex(o_fb)
    o_xsucc = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-11111100f001",
                            "relationships": [edge(o_fb_root, relation="supersedes")]}, signer)
    write_case("outcome-relation-signer-unauthorized",
               {"receipt.json": o_xsucc, "pub.b64": x_pub, "related_b.json": o_fb, "policy.json": pol_b},
               base_case("outcome-relation-signer-unauthorized",
                         {"exitCode": 3, "lineage": "VERIFIED",
                          "errorContains": "RELATION_SIGNER_UNAUTHORIZED"},
                         "WP-B: relation_signer enforced on the OUTCOME path — the successor ring X is "
                         "not in the pinned set → RELATION_SIGNER_UNAUTHORIZED, exit 3 (wortgleich to "
                         "the decision path).",
                         related=["related_b.json"], related_pubs=[y_pub], policy="policy.json",
                         kind="outcome_relation"))

    o_r0 = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-1111110000r0"}, signer)
    o_r0_root = content_root_hex(o_r0)
    o_rx = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-1111110000rx"}, signer)
    o_rx_root = content_root_hex(o_rx)
    o_child_rx = emit_outcome({"outcomeId": "urn:uuid:11111111-1111-1111-1111-111111000rxc",
                               "relationships": [edge(o_rx_root, relation="supersedes")]}, signer)
    o_pol_target = {"schema": V02, "policy_id": "o-reltgt-r0",
                    "relations": {"require_relation_target": {"supersedes": [o_r0_root]}}}
    write_case("outcome-decoy-parent-target-mismatch",
               {"receipt.json": o_child_rx, "pub.b64": x_pub, "related_r0.json": o_r0,
                "related_rx.json": o_rx, "policy.json": o_pol_target},
               base_case("outcome-relation-decoy-parent-target-mismatch",
                         {"exitCode": 3, "lineage": "VERIFIED",
                          "errorContains": "RELATION_TARGET_MISMATCH"},
                         "WP-B + WP-A2: the decoy-parent fix holds on the OUTCOME path too — child "
                         "supersedes->RX (valid) is rejected under require_relation_target pinning R0, "
                         "exit 3, RELATION_TARGET_MISMATCH.",
                         related=["related_r0.json", "related_rx.json"],
                         related_pubs=[x_pub, x_pub], policy="policy.json",
                         kind="outcome_relation", attribution=loek))

    print("done")


if __name__ == "__main__":
    main()
