#!/usr/bin/env python3
"""Generate the relation/v0.1 conformance vectors (run ONCE, fixtures are committed bytes).

Provenance: relation/v0.1 lineage profile (3.3.0, EXPERIMENTAL). The five skeleton vectors
carry crossFormatId xfmt-c0/t1..t4 per the No Silent Landing shared-vector convention
(PB-LINEAGE-XFMT-SYNC-20260715 §1); superset vectors (cycle, depth, unauthorized-signer,
declared-unresolved, retracts-then-use, malformed-digest F6, one per relation) carry none.
All signing keys are FRESH THROWAWAY TEST KEYS generated at build time and never stored —
every receipt verifies via its embedded/derived public key material recorded in pub.b64.

Regeneration changes bytes (fresh keys) — treat like any fixture regeneration: rerun this
script, re-review the diff, recommit. Never hand-edit generated fixtures.
"""
from __future__ import annotations

import base64
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "src"))

from proofbundle import anchors, dsse  # noqa: E402
from proofbundle.decision import emit_decision_receipt  # noqa: E402
from proofbundle.emit import generate_signer  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
EXAMPLES = HERE.parents[1] / "examples"

BASE_PRED = json.loads((EXAMPLES / "decision_receipt_deny.json").read_text(encoding="utf-8"))


def edge(target_hex: str, relation: str = "supersedes", **extra) -> dict:
    e = {"relation": relation,
         "targetReceiptDigest": {"digestAlgorithm": "jcs-sha256-v1", "digest": target_hex}}
    e.update(extra)
    return e


def content_root_hex(env: dict) -> str:
    return anchors.statement_content_root(dsse.load_payload(env)).hex()


def emit(pred_patch: dict | None, signer) -> dict:
    pred = json.loads(json.dumps(BASE_PRED))
    if pred_patch:
        pred.update(pred_patch)
    return emit_decision_receipt(pred, signer, strict=True)


def write_case(name: str, files: dict, case: dict) -> None:
    d = HERE / name
    d.mkdir(parents=True, exist_ok=True)
    for fname, obj in files.items():
        if isinstance(obj, (dict, list)):
            (d / fname).write_text(json.dumps(obj, indent=1, ensure_ascii=False) + "\n",
                                   encoding="utf-8")
        else:
            (d / fname).write_text(str(obj), encoding="utf-8")
    (d / "case.json").write_text(json.dumps(case, indent=2, ensure_ascii=False) + "\n",
                                 encoding="utf-8")
    print("wrote", name)


def base_case(case_id: str, expected: dict, rationale: str, *, related=None, policy=None,
              cross_format_id: str | None = None) -> dict:
    c = {
        "caseId": case_id,
        "kind": "decision_relation",
        "input": "receipt.json",
        "pub": "pub.b64",
        "expected": expected,
        "specRefs": ["docs/design/RELATION_V01_DESIGN.md", "SPEC.md"],
        "rationale": rationale,
        "testKeys": "fresh throwaway keys, generated by conformance/relation/generate_vectors.py",
    }
    if related:
        c["related"] = related
    if policy:
        c["policy"] = policy
    if cross_format_id:
        c["crossFormatId"] = cross_format_id
    return c


def main() -> None:
    signer = generate_signer()          # der Haupt-Aussteller (same-key-Vertrag)
    stranger = generate_signer()        # fremder Signer (unauthorized-signer-Vektor)
    pub_b64 = base64.b64encode(signer.public_key().public_bytes_raw()).decode()

    # Vorgaenger B (gemeinsame Basis vieler Vektoren)
    b_env = emit({"decisionId": "d-predecessor"}, signer)
    b_root = content_root_hex(b_env)

    # 1) valid-baseline (xfmt-c0): keine relationships -> exit 0, lineage null/NOT_EVALUATED
    a0 = emit({"decisionId": "d-baseline"}, signer)
    write_case("valid-baseline",
               {"receipt.json": a0, "pub.b64": pub_b64},
               base_case("relation-valid-baseline",
                         {"exitCode": 0, "lineage": None},
                         "Compatibility floor: a receipt without the profile verifies exactly as "
                         "before; lineage stays NOT_EVALUATED (reported null).",
                         cross_format_id="xfmt-c0"))

    # 2) silent-landing (xfmt-t1, benannter Kernvektor): alte Identitaet, neue Bytes,
    #    KEINE erklaerte Relation -> Krypto-FAIL exit 1.
    a1 = emit({"decisionId": "d-baseline"}, signer)
    body = json.loads(base64.b64decode(a1["payload"]))
    body["predicate"]["decision"]["humanReadableSummary"] = "silently swapped content"
    a1_tampered = dict(a1, payload=base64.b64encode(
        json.dumps(body, separators=(",", ":")).encode()).decode())
    write_case("silent-landing",
               {"receipt.json": a1_tampered, "pub.b64": pub_b64},
               base_case("relation-silent-landing",
                         {"exitCode": 1},
                         "The core must-fail: new bytes presented under the old receipt's "
                         "identity with NO declared relation — indistinguishable from tampering, "
                         "and it FAILS (crypto, exit 1). Legitimate change becomes visible; "
                         "impersonation does not.",
                         cross_format_id="xfmt-t1"))

    # 3) declared-supersedes-verified (xfmt-t2)
    a2 = emit({"decisionId": "d-successor",
               "relationships": [edge(b_root, relation="supersedes",
                                      reasonCode="correction",
                                      declaredAt="2026-07-16T00:00:00Z")]}, signer)
    write_case("declared-supersedes-verified",
               {"receipt.json": a2, "pub.b64": pub_b64, "related_b.json": b_env},
               base_case("relation-declared-supersedes-verified",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "Declared supersession with the predecessor attached and standalone-"
                         "verified: lineage VERIFIED. Proves the declared derivation, never that "
                         "the successor is better or true (claim boundary).",
                         related=["related_b.json"], cross_format_id="xfmt-t2"))

    # 4) digest-mismatch (xfmt-t3): Kante zeigt auf FALSCHEN Digest; Policy verlangt Aufloesung
    wrong = "0" * 63 + "1"
    a3 = emit({"decisionId": "d-mismatch",
               "relationships": [edge(wrong, relation="supersedes")]}, signer)
    pol3 = {"schema": "proofbundle/trust-policy/v0.2", "policy_id": "relation-t3",
            "relations": {"require_relation_resolution": ["supersedes"]}}
    write_case("digest-mismatch",
               {"receipt.json": a3, "pub.b64": pub_b64, "related_b.json": b_env,
                "policy.json": pol3},
               base_case("relation-digest-mismatch",
                         {"exitCode": 3, "lineage": "DECLARED_UNRESOLVED",
                          "errorContains": "LINEAGE_REQUIREMENT_FAILED"},
                         "Parent digest mismatch (shared T3): the edge names a digest the attached "
                         "predecessor does NOT have, so the required relation cannot resolve — the "
                         "policy turns that into a hard FAIL (exit 3, LINEAGE_REQUIREMENT_FAILED). "
                         "The mismatch manifests as failure-to-resolve because attached targets are "
                         "keyed by their COMPUTED content root (a lying edge never finds a target).",
                         related=["related_b.json"], policy="policy.json",
                         cross_format_id="xfmt-t3"))

    # 5) renews-vector (xfmt-t4)
    a4 = emit({"decisionId": "d-renewal",
               "relationships": [edge(b_root, relation="renews")]}, signer)
    write_case("renews-vector",
               {"receipt.json": a4, "pub.b64": pub_b64, "related_b.json": b_env},
               base_case("relation-renews-vector",
                         {"exitCode": 0, "lineage": "VERIFIED"},
                         "Evidence renewal (shared T4): renews = same evidence, new anchors — "
                         "explicitly disjoint from supersedes; the original's identity and age stay "
                         "visible (the predecessor stays attached and valid for its bytes).",
                         related=["related_b.json"], cross_format_id="xfmt-t4"))

    # 6-9) je Relation ein Vektor (supersedes via t2, renews via t4 abgedeckt)
    for rel in ("revises", "corrects", "retracts", "derivedFrom", "amends"):
        env = emit({"decisionId": f"d-{rel.lower()}",
                    "relationships": [edge(b_root, relation=rel)]}, signer)
        write_case(f"relation-{rel.lower()}",
                   {"receipt.json": env, "pub.b64": pub_b64, "related_b.json": b_env},
                   base_case(f"relation-edge-{rel.lower()}",
                             {"exitCode": 0, "lineage": "VERIFIED"},
                             f"One vector per relation: a {rel} edge onto the attached, verified "
                             "predecessor resolves to lineage VERIFIED with the relation's own "
                             "semantics (mapping table in the SPEC chapter).",
                             related=["related_b.json"]))

    # 10) declared-unresolved: Kante ohne beigelegtes Ziel -> kein Fehler, kein PASS-Upgrade
    a10 = emit({"decisionId": "d-unresolved",
                "relationships": [edge(b_root, relation="supersedes")]}, signer)
    write_case("declared-unresolved",
               {"receipt.json": a10, "pub.b64": pub_b64},
               base_case("relation-declared-unresolved",
                         {"exitCode": 0, "lineage": "DECLARED_UNRESOLVED"},
                         "Edge present, target not attached: explicitly NOT an error, but never "
                         "more than declared — no PASS upgrade (lattice monotonicity)."))

    # 11) depth-exceeded: gerade Kette laenger als MAX_CHAIN_DEPTH=32, rueckwaerts gebaut.
    #    (Ein ECHTER Hash-Zyklus ist mit Content-Root-Adressierung konstruktiv UNMOEGLICH —
    #    der Root eines Belegs enthaelt seine Kanten, eine Rueckkante brauchte den finalen
    #    Root des Nachfolgers: zirkulaere Hash-Abhaengigkeit. Der Cycle-Guard bleibt als
    #    Defense-in-Depth gegen manipulierte related-Maps/Verifier-Bugs UNIT-getestet;
    #    das fixture-realisierbare Tiefen-Limit wird hier end-to-end exerziert.)
    chain = [emit({"decisionId": "d-chain-001"}, signer)]
    for i in range(2, 35):
        prev_root = content_root_hex(chain[-1])
        chain.append(emit({"decisionId": f"d-chain-{i:03d}",
                           "relationships": [edge(prev_root, relation="derivedFrom")]}, signer))
    a11 = chain[-1]                      # R34 = Pruefobjekt
    attached = chain[:-1]                # R1..R33 beigelegt
    files11 = {"receipt.json": a11, "pub.b64": pub_b64}
    rel_names = []
    for i, env in enumerate(attached, start=1):
        fname = f"related_{i:03d}.json"
        files11[fname] = env
        rel_names.append(fname)
    write_case("depth-exceeded", files11,
               base_case("relation-depth-exceeded",
                         {"exitCode": 2, "lineage": "FAIL",
                          "errorContains": "relation:depth_exceeded"},
                         "A straight attached ancestry deeper than the hard cap (32) FAILS with a "
                         "stable code — a resource bound, honestly reported. Real hash CYCLES are "
                         "impossible to construct under content-root addressing (a receipt's root "
                         "contains its own edges); the cycle guard stays unit-tested defense-in-depth.",
                         related=rel_names))

    # 12) unauthorized-signer: Vorgaenger von FREMDEM Key -> attached-but-unverified -> FAIL exit 2
    b_foreign = emit({"decisionId": "d-foreign"}, stranger)
    b_foreign_root = content_root_hex(b_foreign)
    a12 = emit({"decisionId": "d-succ-foreign",
                "relationships": [edge(b_foreign_root, relation="supersedes")]}, signer)
    write_case("unauthorized-signer",
               {"receipt.json": a12, "pub.b64": pub_b64, "related_b.json": b_foreign},
               base_case("relation-unauthorized-signer",
                         {"exitCode": 2, "lineage": "FAIL",
                          "errorContains": "relation:target_verification_failed"},
                         "The attached predecessor is signed by a FOREIGN key (same-key CLI "
                         "contract): attached-but-unverified is present-and-wrong and FAILS hard — "
                         "unlike an absent target, which stays declared-only.",
                         related=["related_b.json"]))

    # 13) malformed-digest (F6, Annex — EIGENER Never-Raise-Vektor, getrennt vom Mismatch).
    #    Der ehrliche Emitter WEIGERT sich, das zu emittieren (fail-closed, gut so) — der Fixture
    #    wird deshalb bewusst auf DSSE-Ebene gecraftet: valide Signatur ueber ein Statement mit
    #    Nicht-Hex-Sentinel im Edge-Digest. Genau das prueft der Vektor: der VERIFIER muss FAIL
    #    melden, nie werfen.
    _ok13 = emit({"decisionId": "d-malformed",
                  "relationships": [edge(b_root, relation="supersedes")]}, signer)
    _body13 = json.loads(base64.b64decode(_ok13["payload"]))
    _body13["predicate"]["relationships"][0]["targetReceiptDigest"]["digest"] = (
        "INTENTIONALLY_WRONG_NATIVE_DIGEST")
    try:
        import rfc8785  # noqa: PLC0415
        _bytes13 = rfc8785.dumps(_body13)
        if isinstance(_bytes13, str):
            _bytes13 = _bytes13.encode()
    except Exception:
        _bytes13 = json.dumps(_body13, separators=(",", ":"), sort_keys=True).encode()
    a13 = dsse.sign_envelope(_bytes13, signer,
                             payload_type="application/vnd.in-toto+json")
    write_case("malformed-digest",
               {"receipt.json": a13, "pub.b64": pub_b64},
               base_case("relation-malformed-digest",
                         {"exitCode": 2, "lineage": "FAIL",
                          "errorContains": "relation:malformed"},
                         "F6 (V0.1A annex): a NON-HEX digest sentinel is its own never-raise vector, "
                         "deliberately separate from digest-MISMATCH — the parser must report FAIL, "
                         "never throw. Exercises the malformed path end-to-end through the CLI."))

    # 14) retracts-then-use: beigelegter verifizierter Beleg RETRACTS das Pruefobjekt + Policy
    a14 = emit({"decisionId": "d-in-use"}, signer)
    a14_root = content_root_hex(a14)
    retractor = emit({"decisionId": "d-retractor",
                      "relationships": [edge(a14_root, relation="retracts",
                                             reasonCode="withdrawal")]}, signer)
    pol14 = {"schema": "proofbundle/trust-policy/v0.2", "policy_id": "relation-retracts",
             "relations": {"reject_superseded": True}}
    write_case("retracts-then-use",
               {"receipt.json": a14, "pub.b64": pub_b64, "related_r.json": retractor,
                "policy.json": pol14},
               base_case("relation-retracts-then-use",
                         {"exitCode": 3,
                          "errorContains": "LINEAGE_REQUIREMENT_FAILED"},
                         "Using a receipt that an attached, verified receipt has RETRACTED: the "
                         "retraction never breaks the target's crypto (it stays valid for its "
                         "bytes), but reject_superseded turns continued automated use into a "
                         "policy blocker (exit 3).",
                         related=["related_r.json"], policy="policy.json"))

    print("done")


if __name__ == "__main__":
    main()
