"""proofbundle verifies an SD-JWT produced by the EXTERNAL reference library.

The fixture tests/fixtures/sdjwt_reference_eddsa.json was generated by
openwallet-foundation-labs/sd-jwt-python (the reference implementation that
produces the IETF/RFC 9901 examples) with an Ed25519 issuer key and two
selectively-disclosable claims. proofbundle must verify both the disclosure-digest
commitments and the EdDSA issuer signature — i.e. it interops with the reference
tool, not just with its own emitter. No network / no sd-jwt dependency at test
time; the SD-JWT is committed.
"""
import json
import unittest
from base64 import b64decode
from pathlib import Path

from proofbundle.sdjwt import verify_sd_jwt

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "sdjwt_reference_eddsa.json"


@unittest.skipIf(not FIXTURE.exists(), "sd-jwt reference fixture not present")
class TestSdJwtReference(unittest.TestCase):
    def setUp(self):
        self.f = json.loads(FIXTURE.read_text(encoding="utf-8"))

    def test_source_documented(self):
        self.assertIn("sd-jwt-python", self.f["source"])

    def test_proofbundle_verifies_reference_sd_jwt(self):
        res = verify_sd_jwt(self.f["compact"], b64decode(self.f["issuer_public_key_b64"]))
        self.assertTrue(res["structure_ok"], res)
        self.assertTrue(res["sig_ok"], res)
        self.assertIn("2 disclosure", res["detail"])

    def test_wrong_issuer_key_is_rejected(self):
        # a different key must fail the issuer-signature check (no false accept).
        import os
        res = verify_sd_jwt(self.f["compact"], os.urandom(32))
        self.assertFalse(res.get("sig_ok"), res)
