"""A pull request carries a milestone and ends its description with the house footer.

Owner decision 2026-09-28: every pull request in this repository carries a milestone from the moment
it opens. Its description ends with exactly the two lines of the house footer, and it carries no
tool attribution, no session link and neither of the two retired closing sentences.
`scripts/b7_pr_form_gate.py` judges the three from the event payload the runner writes.

EVERY RULE HAS RED CASES ONLY IT CAN CATCH. An attribution placed before a correct footer is
invisible to the footer rule, so only rule (c) can turn it red; a description with the footer and
nothing else wrong is red only through a missing milestone. Each red case asserts which rule named
it and that the other two stayed silent, so a rule that is removed or weakened turns its own cases
red instead of hiding behind a neighbour.

The tool and address names in the cases are placeholders. The rules are written against the form
of an attribution and of a session link, not against a list of names.
"""
import importlib.util
import itertools
import json
import pathlib
import shutil
import subprocess
import sys
import unicodedata
import urllib.parse

import pytest

REPO = pathlib.Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location(
    "pr_form_gate", REPO / "scripts" / "b7_pr_form_gate.py")
GATE = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(GATE)

LINE_1 = "Written by an AI session of b7n0de under owner review."
LINE_2 = "Measurement, not certification."
FOOTER = LINE_1 + "\n\n" + LINE_2
TEXT = "`abc1234` carries every change below.\n\n## Marking"
BODY = TEXT + "\n\n" + FOOTER
MILESTONE = {"number": 2, "title": "6.3.0", "state": "open"}

RETIRED_1 = ("Written by the operating agent under a standing owner authorisation for Codex threads; "
             "measurements are its own, at the head named above.")
RETIRED_2 = "Prepared with AI agent involvement, reviewed and submitted under human oversight."


def _judge(tmp_path, capsys, *, body=BODY, milestone=MILESTONE, drop=()):
    pr = {"number": 1, "body": body, "milestone": milestone}
    for key in drop:
        del pr[key]
    event = tmp_path / "event.json"
    event.write_text(json.dumps({"action": "edited", "pull_request": pr}), encoding="utf-8")
    code = GATE.main(["--event", str(event)])
    return code, capsys.readouterr().out


def _rules(out: str) -> set:
    return {r for r in ("(a)", "(b)", "(c)") if r in out}


# ------------------------------------------------------------------------------------------------
# Green
# ------------------------------------------------------------------------------------------------

@pytest.mark.parametrize("body", [
    BODY,
    FOOTER,
    BODY + "\n",
    BODY + "\r\n",
    BODY.replace("\n", "\r\n"),
    TEXT + "\n\nThe wheel was generated with setuptools 69.5.1.\n\n" + FOOTER,
    TEXT + "\n\nSee [the session guide](https://docs.example.org/sessions.html).\n\n" + FOOTER,
    TEXT + "\n\nA session_id field is read as given.\n\n" + FOOTER,
    TEXT + "\n\nThe table was generated by hand, see [the guide](https://docs.example.org/).\n\n" + FOOTER,
    # Codex thread 4217549821: a bracketed label with no definition renders as its text, so it is prose.
    TEXT + "\n\nGenerated by [release tooling] from the tag.\n\n" + FOOTER,
    TEXT + "\n\nGenerated by [release tooling][nowhere] from the tag.\n\n" + FOOTER,
    TEXT + "\n\nGenerated by [release tooling][] from the tag.\n\n" + FOOTER,
    # Codex thread 4217549831: a session-shaped part of the query or the fragment is not a path segment.
    TEXT + "\n\nSee https://example.org/docs?next=/session_123 for the steps.\n\n" + FOOTER,
    TEXT + "\n\nSee https://example.org/docs#/sessions/0000 for the steps.\n\n" + FOOTER,
    # Codex thread 4218677417: labels told apart by their punctuation are different labels, so the bracketed
    # text stays prose beside a definition of the other one.
    *[TEXT + f"\n\nGenerated by [release{p}tooling] from the tag.\n\n[releasetooling]: https://tool.example/\n\n"
      + FOOTER for p in ("_", "*", "`", "~")],
    # Codex thread 4219686001: resolved as a browser resolves it, `///session_123` is a host and `session_123/..`
    # leaves no session segment in the path.
    TEXT + "\n\nSee [the host](///session_123) for the steps.\n\n" + FOOTER,
    TEXT + "\n\nSee [the parent](session_123/..) for the steps.\n\n" + FOOTER,
    # Codex threads 4220250591 and 4220250628: dot segments of an absolute address, in a link or in the text, are
    # removed as a browser removes them, `%2e` included, and `https:///session_123` names a host.
    TEXT + "\n\nSee [the parent](https://example.org/session_123/..) for the steps.\n\n" + FOOTER,
    TEXT + "\n\nSee [the parent](https://example.org/session_123/%2e%2E) for the steps.\n\n" + FOOTER,
    TEXT + "\n\nSee https://example.org/session_123/.. for the steps.\n\n" + FOOTER,
    TEXT + "\n\nSee https:///session_123 for the steps.\n\n" + FOOTER,
    # Codex thread 4220777711: %5C is data in its segment, so these paths have no session segment
    TEXT + "\n\nSee [the note](https://example.org/%5Csession_123) for it.\n\n" + FOOTER,
    TEXT + "\n\nSee [the note](https://example.org/%5Csessions/0000) for it.\n\n" + FOOTER,
    # Codex thread 4221642871: a special scheme other than the base's reads any slash run as the start of the host
    TEXT + "\n\nSee [the host](http:/session_123) for it.\n\n" + FOOTER,
    TEXT + "\n\nSee [the host](ftp:session_123) for it.\n\n" + FOOTER,
    # Codex thread 4222922549: a backslash before an IPv6 host is a slash, and the host does not decide the path
    TEXT + '\n\nSee <a href="http://\\[::1]/ok">run</a> for it.\n\n' + FOOTER,
    TEXT + '\n\nSee <a href="https://u[s:p@tool.example/ok">run</a> for it.\n\n' + FOOTER,
    # Codex thread 4222922558: only C0 controls and the space are trimmed, so the segment begins with the other space
    TEXT + '\n\nSee <a href="&nbsp;session_123">run</a> for it.\n\n' + FOOTER,
    TEXT + '\n\nSee <a href="&#x2003;session_123">run</a> for it.\n\n' + FOOTER,
], ids=["body", "footer-only", "trailing-lf", "trailing-crlf", "crlf", "prose-generated-with",
        "prose-sessions-page", "prose-session-id", "prose-generated-by-then-a-link",
        "undefined-shortcut-reference", "undefined-full-reference", "undefined-collapsed-reference",
        "session-in-the-query", "session-in-the-fragment", "label-with-underscore", "label-with-star",
        "label-with-backtick", "label-with-tilde", "triple-slash-is-a-host", "dot-segment-resolved-away",
        "absolute-dot-segment", "absolute-encoded-dot-segment", "text-dot-segment", "text-triple-slash-is-a-host",
        "encoded-backslash-is-data", "encoded-backslash-before-sessions", "http-one-slash-is-a-host",
        "ftp-no-slash-is-a-host", "backslash-before-an-ipv6-host", "bracket-in-the-user-name",
        "leading-no-break-space", "leading-em-space"])
def test_green_a_milestone_and_the_footer_as_the_last_text(tmp_path, capsys, body):
    code, out = _judge(tmp_path, capsys, body=body)
    assert code == 0, out
    assert out.splitlines()[0] == "pr-form: green"


# ------------------------------------------------------------------------------------------------
# (a) the milestone
# ------------------------------------------------------------------------------------------------

@pytest.mark.parametrize("milestone", [None, {}, {"title": ""}, {"title": "   "}, {"title": 3},
                                       "6.3.0", 2, [MILESTONE]],
                         ids=["none", "empty-object", "empty-title", "blank-title", "number-title",
                              "string", "number", "list"])
def test_red_a_without_a_milestone(tmp_path, capsys, milestone):
    code, out = _judge(tmp_path, capsys, milestone=milestone)
    assert code == 1
    assert _rules(out) == {"(a)"}, out


def test_red_a_a_payload_without_the_milestone_field(tmp_path, capsys):
    code, out = _judge(tmp_path, capsys, drop=("milestone",))
    assert code == 1
    assert _rules(out) == {"(a)"} and "NOT MEASURABLE" in out, out


# ------------------------------------------------------------------------------------------------
# (b) the footer is the last text, exactly
# ------------------------------------------------------------------------------------------------

@pytest.mark.parametrize("body", [
    None,
    "",
    TEXT,
    TEXT + "\n\n" + LINE_2 + "\n\n" + LINE_1,
    TEXT + "\n\n" + LINE_2,
    TEXT + "\n\n" + LINE_1,
    TEXT + "\n\n" + LINE_1 + "\n" + LINE_2,
    TEXT + "\n\n" + LINE_1 + "\n\n\n" + LINE_2,
    TEXT + "\n\n" + LINE_1 + "\n \n" + LINE_2,
    BODY + " ",
    BODY + "\n\nThanks.",
    TEXT + "\n\n```\n" + FOOTER + "\n```",
    TEXT + "\n\nMarking: " + FOOTER,
    BODY.replace("owner review", "owner review"),
    BODY.replace("session", "ses​sion"),
    BODY.replace("\n\n" + LINE_2, "\r\r" + LINE_2),
    BODY.replace("certification", "certification\u0000"),
], ids=["null", "empty", "no-footer", "swapped", "second-line-only", "first-line-only",
        "no-blank-line", "two-blank-lines", "blank-line-with-space", "trailing-space", "text-after",
        "in-a-code-fence", "glued-to-text", "no-break-space", "zero-width-space", "bare-cr", "nul"])
def test_red_b_the_description_does_not_end_with_the_footer(tmp_path, capsys, body):
    code, out = _judge(tmp_path, capsys, body=body)
    assert code == 1
    assert _rules(out) == {"(b)"}, out


def test_red_b_a_description_of_another_type_is_not_measurable(tmp_path, capsys):
    code, out = _judge(tmp_path, capsys, body=["a", "list"])
    assert code == 1
    assert "(b)" in out and "NOT MEASURABLE" in out, out


# ------------------------------------------------------------------------------------------------
# (c) no attribution, no session link, no retired sentence, anywhere
# ------------------------------------------------------------------------------------------------

_BEFORE_THE_FOOTER = {
    "robot-form": "\U0001F916 Generated with [ExampleTool](https://tool.example/)",
    "rule-form": "---\n_Generated by [ExampleTool](https://tool.example/code/session_0000)_",
    "attribution-link-only": "Generated by [ExampleTool](https://tool.example/)",
    "attribution-bold": "**Generated with** [ExampleTool](https://tool.example/)",
    "attribution-wrapped": "Generated\nwith [ExampleTool](https://tool.example/)",
    # Every other way to write a link after the words (a review thread on 59c96fa5): a reference link in
    # its full, collapsed and shortcut form, an autolink, a bare address and an HTML anchor.
    "attribution-reference-link": "Generated by [ExampleTool][tool]\n\n[tool]: https://tool.example/",
    "attribution-collapsed-reference": "Generated by [ExampleTool][]\n\n[exampletool]: https://tool.example/",
    "attribution-shortcut-reference": "Generated by [ExampleTool]\n\n[ExampleTool]: https://tool.example/",
    "attribution-autolink": "Generated with <https://tool.example/>",
    "attribution-bare-address": "Generated with https://tool.example/",
    "attribution-html-anchor": 'Generated by <a href="https://tool.example/">ExampleTool</a>',
    "session-link": "https://tool.example/code/session_0000",
    "session-link-without-scheme": "tool.example/code/session_0000",
    "session-link-in-markdown": "[the session](https://tool.example/sessions/0000)",
    "session-link-upper-case": "HTTPS://TOOL.EXAMPLE/CODE/SESSION_0000",
    "session-link-zero-width": "https://tool.example/code/ses​sion_0000",
    "session-link-entity": "https://tool&#46;example/code/session&#95;0000",
    "session-link-escaped": "https://tool.example/code/session\\_0000",
    # The same address with its path percent-encoded, which the server decodes, and in a reference
    # definition.
    "session-link-percent-encoded": "https://tool.example/code/%73ession_0000",
    "session-link-percent-encoded-separator": "https://tool.example/code/session%5F0000",
    "session-link-reference-definition": "[the run]\n\n[the run]: https://tool.example/code/session_0000",
    # Codex thread 4218677402: a definition is a definition wherever CommonMark reads one, its destination on the
    # next line, in a block quote or in a list item.
    "attribution-definition-on-the-next-line": "Generated by [ExampleTool][tool]\n\n[tool]:\n  https://tool.example/",
    "attribution-definition-in-a-block-quote": "Generated by [ExampleTool][tool]\n\n> [tool]: https://tool.example/",
    "attribution-definition-in-a-list-item": "Generated by [ExampleTool][tool]\n\n- [tool]: https://tool.example/",
    "attribution-in-an-html-block": '<p>Generated by <a href="https://tool.example/">ExampleTool</a></p>',
    # Codex thread 4218677425: any host after a scheme, and every link target, a relative one included.
    "session-link-localhost": "https://localhost/code/session_0000",
    "session-link-ipv6-autolink": "<http://[::1]/sessions/0000>",
    "session-link-relative": "[the run](/code/session_0000)",
    "session-link-relative-reference": "[the run]\n\n[the run]: /sessions/0000",
    # Codex thread 4219210671: a target without a leading slash is a relative path, not a host.
    "session-link-rootless-target": "[run](session_123)",
    "session-link-rootless-sessions-target": "[run](sessions/0000)",
    "session-link-rootless-reference": "[run]\n\n[run]: code/session_0000",
    # Codex thread 4219686001, the inverse surface: a backslash is a slash in a special URL.
    "session-link-backslash-path": "[run](\\sessions\\0000)",
    "session-link-backslash-after-host": "[run](https://tool.example\\code\\session_0000)",
    "session-link-backslash-in-an-anchor": '<a href="\\code\\session_0000">run</a>',
    # the controls of thread 4220250628: a dot segment that leaves the session segment in the path stays red
    "session-link-single-dot-after": "[run](https://tool.example/session_0000/.)",
    "session-link-after-a-parent": "[run](https://tool.example/a/%2e%2e/session_0000)",
    "session-address-after-a-parent": "see https://tool.example/a/../session_0000 for it",
    # Codex thread 4220777693: an opaque path keeps its dot segments, as a browser keeps them
    "session-link-opaque-mailto": "[run](mailto:session_0000/..)",
    "session-link-opaque-custom-scheme": "[run](tool:session_0000/.)",
    # Codex threads 4221178333 and 4221178345: a backslash after the host of any special scheme, and an uppercase
    # letter that only percent-decoding reveals
    "session-link-ftp-backslash": "[run](ftp://tool.example\\session_0000)",
    "session-link-wss-backslash": "[run](wss://tool.example\\code\\session_0000)",
    "session-link-encoded-uppercase": "[run](https://tool.example/%53ession_0000)",
    "session-link-encoded-uppercase-sessions": "[run](https://tool.example/%53ESSIONS/0000)",
    # Codex thread 4221642886: the whole fold after decoding, NFKC and format characters included; and the base's
    # own scheme with one slash stays a path, as the control of thread 4221642871
    "session-link-encoded-fullwidth": "[run](https://tool.example/%EF%BC%B3ession_0000)",
    "session-link-encoded-format-character": "[run](https://tool.example/ses%E2%80%8Bsion_0000)",
    "session-link-same-scheme-one-slash": "[run](https:/session_0000)",
    # Codex thread 4222119964: a file URL keeps its slash runs as path
    "session-link-file-three-slashes": '<a href="file:///session_0000">run</a>',
    "session-link-file-four-slashes": "[run](file:////sessions/0000)",
    # Codex threads 4222922549 and 4222922558, the controls: the same forms with a session segment, a space a browser
    # keeps at the end, and a tab it removes
    "session-link-backslash-before-an-ipv6-host": '<a href="http://\\[::1]/session_0000">run</a>',
    "session-link-scheme-relative-ipv6": '<a href="\\\\[::1]\\sessions\\0000">run</a>',
    "session-link-bracket-in-the-user-name": '<a href="https://u[s:p@tool.example/session_0000">run</a>',
    "session-link-trailing-no-break-space": '<a href="session_0000&nbsp;">run</a>',
    "session-link-tab-inside": '<a href="ses&#9;sion_0000">run</a>',
    # Codex threads 4224159486 and 4224159495: a letter that folds to an ASCII letter is no scheme, and a dot segment at
    # the end leaves a slash after the session segment
    "session-link-long-s-is-no-scheme": "[run](\u017f://session_0000)",
    "session-link-sharp-s-is-no-scheme": "[run](\u00df://session_0000)",
    "session-link-sessions-then-parent": "[run](https://tool.example/sessions/x/..)",
    "session-link-sessions-then-encoded-parent": "[run](https://tool.example/sessions/x/%2e%2e)",
    "session-link-sessions-then-dot": "[run](tool:/sessions/x/.)",
    "retired-1": RETIRED_1,
    "retired-1-wrapped": RETIRED_1.replace(" a standing ", " a standing\n"),
    "retired-1-upper-case": RETIRED_1.upper(),
    "retired-1-italic": "_" + RETIRED_1 + "_",
    "retired-1-us-spelling": RETIRED_1.replace("authorisation", "authorization"),
    "retired-1-emphasis-inside": RETIRED_1.replace("operating agent", "*operating* agent"),
    "retired-2": RETIRED_2,
    "retired-2-wrapped-as-in-agents-md": RETIRED_2.replace("human oversight", "human\noversight"),
    "retired-2-no-break-space": RETIRED_2.replace("human oversight", "human oversight"),
}


@pytest.mark.parametrize("inserted", list(_BEFORE_THE_FOOTER.values()), ids=list(_BEFORE_THE_FOOTER))
def test_red_c_only_the_attribution_rule_can_see_it_before_a_correct_footer(tmp_path, capsys, inserted):
    code, out = _judge(tmp_path, capsys, body=TEXT + "\n\n" + inserted + "\n\n" + FOOTER)
    assert code == 1
    assert _rules(out) == {"(c)"}, out


def test_red_c_without_the_parser_is_not_measurable(tmp_path, capsys, monkeypatch):
    """What renders as a link is decided by the CommonMark parser; without it rule (c) cannot read the
    description, and that is red, never a pass."""
    monkeypatch.setattr(GATE, "MarkdownIt", None)
    code, out = _judge(tmp_path, capsys)
    assert code == 1
    assert _rules(out) == {"(c)"} and "NOT MEASURABLE" in out, out


def test_red_c_a_link_target_urllib_cannot_resolve_is_not_measurable(tmp_path, capsys, monkeypatch):
    """A form urlsplit refuses and the resolver does not yet know is rule (c) unread, red with its reason, never an
    uncaught exception (Codex thread 4222922549: exit 1 without a reason)."""
    def refuses(*_args, **_kwargs):
        raise ValueError("Invalid IPv6 URL")
    monkeypatch.setattr(GATE.urllib.parse, "urljoin", refuses)
    code, out = _judge(tmp_path, capsys, body=TEXT + "\n\nSee [the guide](https://docs.example.org/).\n\n" + FOOTER)
    assert code == 1
    assert _rules(out) == {"(c)"} and "NOT MEASURABLE" in out, out


#: A browser's own URL parser, the WHATWG one in Node, as the oracle for how a link target resolves on the page.
_ORACLE = """
const base = "https://github.com/b7n0de/proofbundle/pull/1";
const targets = JSON.parse(require("fs").readFileSync(0, "utf8"));
process.stdout.write(JSON.stringify(targets.map(t => { try { return new URL(t, base).pathname; } catch (e) {
  return null; } })));
"""


def _generated_targets() -> list:
    """Every combination of the parts the review rounds of pull request 308 varied, each with the edges a browser
    trims or keeps: a scheme, the slashes and backslashes after it, an authority, a path, and a character at each end."""
    # round twelve (Codex threads 4224159486 and 4224159495): letters that fold to an ASCII letter, and a dot segment
    # at the end of a path that keeps a session segment followed by a slash
    schemes = ["", "http:", "https:", "ftp:", "ws:", "wss:", "file:", "tool:", "mailto:", "HTTP:", "\u017f:",
               "\u00df:", "\u212a:", "\u0130:"]
    slashes = ["", "/", "//", "///", "\\", "\\\\", "/\\", "\\/"]
    authorities = ["", "h.example", "[::1]", "\\[::1]", "u[s:p@h.example", "[::1", "h.example:80", "a@b@h.example"]
    paths = ["/session_1", "\\session_1", "/sessions/0", "/a/../session_1", "/session_1/..", "/session_1/%2e%2E",
             "session_1", "/%5Csession_1", "/ok", "?x=/session_1", "#/session_1", "/a/%2e./session_1",
             "/sessions/x/..", "/sessions/x/.", "/sessions/x/%2E%2e", "/sessions"]
    edges = [("", ""), ("\u00a0", ""), ("\u2003", ""), (" ", ""), ("\t", ""), ("\x01", "\x1f"), ("", "\u00a0"),
             ("\n", " ")]
    return sorted({left + s + sl + a + p + right for s, sl, a, p, (left, right)
                   in itertools.product(schemes, slashes, authorities, paths, edges)})


def _oracle_has_session_segment(pathname: str) -> bool:
    """The session rule over the path the oracle resolved, its segments folded as the gate folds them."""
    segments = ["".join(c for c in unicodedata.normalize("NFKC", urllib.parse.unquote(s))
                        if unicodedata.category(c) != "Cf").casefold() for s in pathname.split("/")]
    return any(GATE._SESSION_SEGMENT.match(s) or (s in ("session", "sessions") and i + 1 < len(segments))
               for i, s in enumerate(segments))


@pytest.mark.skipif(shutil.which("node") is None, reason="the oracle is the WHATWG URL parser of Node, not installed")
def test_every_generated_target_resolves_as_a_browser_resolves_it():
    """Codex threads 4222922549 and 4222922558 found two steps before the parse that a browser does not take. The
    class is any such step, so the resolver is held to a browser's parser over the generated combinations instead of
    one case per finding. Where the browser resolves the target, the gate reads the same session segment or none;
    where the browser refuses it, the gate may read the path for a session segment, stricter and never looser, and it
    never raises."""
    targets = _generated_targets()
    done = subprocess.run(["node", "-e", _ORACLE], input=json.dumps(targets), capture_output=True, text=True,
                          timeout=300, check=True)
    pathnames = json.loads(done.stdout)
    assert len(pathnames) == len(targets) > 100000, "control: the oracle answered every generated target"
    resolved = [(t, p) for t, p in zip(targets, pathnames) if p is not None]
    assert len(resolved) > 80000, "control: the browser resolves most of the generated targets"
    differ = [(t, p) for t, p in resolved
              if GATE._session_path(t, aus_text=False) is not _oracle_has_session_segment(p)]
    assert not differ, differ[:10]
    for t, p in zip(targets, pathnames):
        if p is None:
            GATE._session_path(t, aus_text=False)       # a target the browser refuses is read, never an exception


def test_red_b_and_c_the_form_a_tool_appends_after_the_footer(tmp_path, capsys):
    appended = ("\n\n\U0001F916 Generated with [ExampleTool](https://tool.example/tool)\n\n"
                "https://tool.example/code/session_0000")
    code, out = _judge(tmp_path, capsys, body=BODY + appended)
    assert code == 1
    assert _rules(out) == {"(b)", "(c)"}, out


def test_red_b_and_c_a_retired_sentence_after_the_footer(tmp_path, capsys):
    code, out = _judge(tmp_path, capsys, body=BODY + "\n\n" + RETIRED_1 + "\n")
    assert code == 1
    assert _rules(out) == {"(b)", "(c)"}, out


def test_red_a_b_and_c_are_named_together(tmp_path, capsys):
    code, out = _judge(tmp_path, capsys, milestone=None, body=TEXT + "\n\n" + RETIRED_2)
    assert code == 1
    assert _rules(out) == {"(a)", "(b)", "(c)"}, out


# ------------------------------------------------------------------------------------------------
# What the gate prints, and what it does with an input it cannot read
# ------------------------------------------------------------------------------------------------

@pytest.mark.parametrize("body", [
    TEXT + "\n::error::MARKER-7f3a\n::stop-commands::MARKER-7f3a\n\n" + FOOTER,
    "::warning::MARKER-7f3a\n" + RETIRED_1,
])
def test_no_byte_of_the_description_reaches_the_output(tmp_path, capsys, body):
    """The runner reads workflow commands from stdout, and the description is text anyone who can
    open a pull request writes. The gate prints fixed reasons, never the description."""
    _, out = _judge(tmp_path, capsys, body=body)
    assert "MARKER-7f3a" not in out
    assert not any(line.startswith("::") for line in out.splitlines()), out


def test_a_milestone_title_is_printed_on_one_line(tmp_path, capsys):
    code, out = _judge(tmp_path, capsys, milestone={"title": "6.3.0\n::error::MARKER-7f3a"})
    assert code == 0
    assert not any(line.startswith("::") for line in out.splitlines()), out


@pytest.mark.parametrize("content", [None, b"not json", b"[1, 2]", b'{"action": "edited"}',
                                     b'{"pull_request": null}', b'{"pull_request": "x"}',
                                     b"\xff\xfe"],
                         ids=["missing-file", "not-json", "list", "no-pull-request",
                              "null-pull-request", "string-pull-request", "not-utf-8"])
def test_red_an_event_payload_the_gate_cannot_read(tmp_path, capsys, content):
    event = tmp_path / "event.json"
    if content is not None:
        event.write_bytes(content)
    code = GATE.main(["--event", str(event)])
    out = capsys.readouterr().out
    assert code == 1
    assert "NOT MEASURABLE" in out, out


def test_the_script_exits_0_and_1_when_the_step_runs_it(tmp_path):
    script = REPO / "scripts" / "b7_pr_form_gate.py"
    codes = []
    for milestone in (MILESTONE, None):
        event = tmp_path / "event.json"
        event.write_text(json.dumps({"pull_request": {"body": BODY, "milestone": milestone}}),
                         encoding="utf-8")
        done = subprocess.run([sys.executable, str(script), "--event", str(event)],
                              capture_output=True, text=True, timeout=60)
        codes.append(done.returncode)
    assert codes == [0, 1]


def test_the_footer_the_gate_holds_is_the_house_footer():
    assert GATE.FOOTER == (LINE_1, LINE_2)
