#!/usr/bin/env python3
"""A pull request carries a milestone, and its description ends with the house footer.

Owner decision 2026-09-28: every pull request in this repository carries a milestone from the moment
it opens. Its description ends with exactly the two lines of the house footer, and it carries no tool
attribution, no session link and neither of the two retired closing sentences. Three rules:

  (a) the pull request has a milestone;
  (b) the description ends with exactly the two footer lines, separated by one empty line;
  (c) the description carries no tool attribution, no session link and no retired sentence.

WHAT IS READ. The event payload the runner writes for this run, `$GITHUB_EVENT_PATH`: the fields
`pull_request.milestone` and `pull_request.body`. No API call, no token. Its own workflow,
`.github/workflows/pr-form.yml`, runs this script and starts a run on `edited`, `milestoned` and
`demilestoned`, so a changed description or milestone is judged by a run that reads the new state;
ci.yml does not run it and does not start on those events.

WHAT (b) ACCEPTS. The two lines byte for byte, with one empty line between them, at the end of the
text or after a line break. A line break is LF or CRLF, because a description saved from the browser
carries CRLF; trailing line breaks after the footer are not text. Anything else after the footer, a
space included, is text after the footer.

WHAT (c) READS. The description is folded before the search: HTML character references resolved,
NFKC, format characters such as a zero-width space removed, case folded, whitespace runs collapsed,
and for the sentences the Markdown emphasis and escape marks dropped. A retired sentence broken over
two lines, in italics or in capitals is the same sentence. The rules name the FORM, not a list of
tools: an attribution is "Generated with" or "Generated by" followed by a link in any form a
description renders (a Markdown link inline or by reference, an autolink, a bare address, an HTML
anchor), and a session link is an address whose path has a segment `session` or `sessions` followed
by `_`, `-` or `/`, read after percent-decoding.

WHAT RENDERS AS A LINK IS DECIDED BY A COMMONMARK PARSER, markdown-it-py, not by a pattern. Three
rounds of review found a form the patterns missed or invented: an undefined reference read as a link,
a definition whose destination stands on the next line or inside a block quote, a label told apart
only by its punctuation (Codex threads 4217549821, 4218677402 and 4218677417 on pull request 308).
The parser resolves references as CommonMark does; its links, autolinks and HTML anchors are the
links. A bare address is not a CommonMark link but GitHub renders it, so text is also scanned for
one, with any host after a scheme (`localhost`, an IPv6 literal) and with `www.`. Every link target
the parser yields counts for the session rule as well, a relative one included (thread 4218677425),
and the path is the path of the parsed address: a segment in its query or fragment is not one
(thread 4217549831). Without the parser rule (c) is NOT MEASURABLE; pr-form.yml installs it from
`.github/pr-form-requirements.txt`, pinned by hash.

LIMITS, said here. An attribution in another form, such as a tool named in plain prose without a
link, is not caught by (c); at the end of a description (b) still refuses it, because nothing may
follow the footer. A re-run of a job reads the payload of its original event and so judges the
description as it stood then; a new event starts a run with a new payload.

WHAT IS PRINTED. Never a byte of the description. The runner reads workflow commands from stdout,
and a description is text anyone who can open a pull request writes. The output names the rules
that failed, in fixed words, and the milestone title through repr on one line.

Exit: 0 green · 1 RED, with the reasons. The contract of the release-scope title gate: an input
this gate cannot read is RED and says NOT MEASURABLE, never a pass.
"""
from __future__ import annotations

import argparse
import html
import html.parser
import json
import pathlib
import re
import sys
import unicodedata
import urllib.parse

try:  # the CommonMark parser that decides what renders as a link (WHAT RENDERS AS A LINK)
    from markdown_it import MarkdownIt
except ImportError:
    MarkdownIt = None

#: The house footer, the two lines in order. Between them one empty line, after them nothing.
FOOTER = ("Written by an AI session of b7n0de under owner review.", "Measurement, not certification.")
_FOOTER_TEXT = FOOTER[0] + "\n\n" + FOOTER[1]

#: The two retired closing sentences, by the part that names each of them. Searched in the folded
#: text, so a line break, emphasis or capitals inside the sentence do not hide it.
_RETIRED = (
    ("the retired closing sentence of the operating agent",
     re.compile(r"written by the operating agent under a standing owner authori[sz]ation")),
    ("the retired closing sentence of human oversight",
     re.compile(r"reviewed and submitted under human oversight")),
)

#: The words of an attribution, as the text before a link ends with them (folded, whitespace collapsed).
_PHRASE = re.compile(r"(?:\A|\W)generated (?:with|by) ?\Z")
#: A bare address GitHub renders as a link: a scheme and any host (`localhost`, an IPv6 literal), or `www.`.
_BARE = r"(?:[a-z][a-z0-9+.-]*://(?:\[[0-9a-f:.]+\])?|www\.)[^\s()\[\]<>]*"
#: The words of an attribution followed by a bare address in the same text.
_PHRASE_THEN_BARE = re.compile(r"(?:\A|\W)generated (?:with|by) <?" + _BARE)
#: An address in the text, scanned for the session rule whether or not it renders: a bare address, or a host
#: with a dot and no scheme. Which part of it is the path is decided by `urllib.parse.urlsplit`.
_ADDRESS = re.compile(_BARE + r"|[a-z0-9-]+(?:\.[a-z0-9-]+)+(?::[0-9]+)?[/?#][^\s()\[\]<>]*")
#: A path segment that begins with `session` or `sessions` and `_` or `-`; or is exactly one of the two words
#: with another segment after it (`/sessions/0000`).
_SESSION_SEGMENT = re.compile(r"\Asessions?[_-]")


def _folded(text: str) -> str:
    text = unicodedata.normalize("NFKC", html.unescape(text))
    text = "".join(c for c in text if unicodedata.category(c) != "Cf")
    return text.casefold()


def _as_prose(folded: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[*_`~\\]", "", folded))


class NotMeasurable(Exception):
    """Rule (c) cannot read the description: the parser is missing or failed."""


class _Anchors(html.parser.HTMLParser):
    """A piece of HTML as the items `_rendered` yields, in order: its text, and each `<a>` as a link."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.items: list[tuple[str, str]] = []

    def handle_starttag(self, tag, attrs):
        if tag == "a":
            self.items.append(("link", next((v for k, v in attrs if k == "href" and v), "")))

    def handle_data(self, data):
        self.items.append(("text", data))


def _anchors(fragment: str) -> list[tuple[str, str]]:
    leser = _Anchors()
    leser.feed(fragment)
    leser.close()
    return leser.items


def _rendered(body: str) -> tuple[list[list[tuple[str, str]]], list[str]]:
    """The description as CommonMark renders it: per run of inline content, its items in order, ("text", ...)
    and ("link", href); and the target of every link it renders (links, resolved references, autolinks, HTML
    anchors)."""
    if MarkdownIt is None:
        raise NotMeasurable("the CommonMark parser markdown-it-py is not installed")
    try:
        tokens = MarkdownIt("commonmark").parse(body)
    except Exception as exc:  # noqa: BLE001 - any failure of the parser leaves (c) unread
        raise NotMeasurable(f"the CommonMark parser failed ({type(exc).__name__})") from exc
    laeufe: list[list[tuple[str, str]]] = []
    ziele: list[str] = []
    for tok in tokens:
        if tok.type == "html_block":
            items = _anchors(tok.content)
            ziele += [z for art, z in items if art == "link"]
            laeufe.append(items)
            continue
        if tok.type != "inline":
            continue
        lauf: list[tuple[str, str]] = []
        for kind in tok.children or []:
            if kind.type == "text":
                lauf.append(("text", kind.content))
            elif kind.type in ("softbreak", "hardbreak"):
                lauf.append(("text", " "))
            elif kind.type == "link_open":
                ziel = str(kind.attrGet("href") or "")
                ziele.append(ziel)
                lauf.append(("link", ziel))
            elif kind.type == "html_inline":
                items = _anchors(kind.content)
                ziele += [z for art, z in items if art == "link"]
                lauf += items
            elif kind.type == "code_inline":
                lauf.append(("text", kind.content))
        laeufe.append(lauf)
    return laeufe, ziele


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", _folded(text))


def _has_attribution(laeufe: list[list[tuple[str, str]]]) -> bool:
    """The words, then a link: rendered (the parser's), or a bare address in the same text."""
    for lauf in laeufe:
        davor = ""
        for art, inhalt in lauf:
            if art == "link":
                if _PHRASE.search(_norm(davor)):
                    return True
                davor = ""
            else:
                davor += inhalt
                if _PHRASE_THEN_BARE.search(_norm(davor)):
                    return True
    return False


#: The address a link target of a pull request description is resolved against, as a browser resolves it there.
_BASIS = "https://github.com/b7n0de/proofbundle/pull/1"


def _aufgeloest(ziel: str) -> str:
    """A link target resolved the way a browser resolves it on a pull request page (WHATWG URL, a special scheme):
    a backslash is a slash, a run of two or more leading slashes starts the host, and dot segments are removed.
    Codex thread 4219686001 on pull request 308: `///session_123` names the host session_123, not the path, and
    `session_123/..` resolves away the segment, while a backslash path was read as no path at all. The parser
    writes a backslash of a Markdown link as `%5C`; it is read as a slash too, which can only make the rule
    stricter."""
    ziel = ziel.strip()
    schema = urllib.parse.urlsplit(ziel).scheme.casefold()
    if schema in ("", "http", "https"):
        ziel = re.sub(r"(?i)%5c", "/", ziel).replace("\\", "/")
        rest = ziel[len(schema) + 1:] if schema else ziel
        if rest.startswith("//"):
            rest = "//" + rest.lstrip("/")
        ziel = (schema + ":" if schema else "") + rest
    return urllib.parse.urljoin(_BASIS, ziel)


def _session_path(adresse: str, *, aus_text: bool) -> bool:
    """Whether the path of an address has a session segment. A link target the parser yields is a URL reference,
    resolved as a browser resolves it on the pull request page (`_aufgeloest`), so `session_123` is a relative path;
    only an address found in the text without a scheme is read as a host first (`tool.example/code/...`). Codex
    thread 4219210671 on pull request 308: the host reading was applied to every target, and a rootless relative
    target became a host with an empty path."""
    adresse = adresse.casefold()
    if aus_text and "://" not in adresse:
        adresse = "//" + adresse          # a host with no scheme, as the text scan finds one
    elif not aus_text:
        adresse = _aufgeloest(adresse)
    segmente = urllib.parse.unquote(urllib.parse.urlsplit(adresse).path).split("/")
    return any(_SESSION_SEGMENT.match(s) or (s in ("session", "sessions") and i + 1 < len(segmente))
               for i, s in enumerate(segmente))


def _has_session_link(folded: str, ziele: list[str]) -> bool:
    """Every link target the parser yields, relative ones included, and every address in the text."""
    return (any(_session_path(a, aus_text=False) for a in ziele)
            or any(_session_path(a, aus_text=True) for a in _ADDRESS.findall(folded.replace("\\", ""))))


def ends_with_footer(body: str) -> bool:
    """(b): the footer lines, exactly, as the last text."""
    text = body.replace("\r\n", "\n").rstrip("\n")
    return text == _FOOTER_TEXT or text.endswith("\n" + _FOOTER_TEXT)


def attribution_findings(body: str) -> list[str]:
    """(c): the names of every form found, in fixed words. NotMeasurable when the parser cannot read it."""
    folded = _folded(body)
    found = [name for name, pattern in _RETIRED if pattern.search(_as_prose(folded))]
    laeufe, ziele = _rendered(body)
    if _has_attribution(laeufe):
        found.append("a tool attribution")
    if _has_session_link(folded, ziele):
        found.append("a session link")
    return found


def judge(payload: object) -> tuple[list[str], str | None]:
    """The reasons for RED, empty when green, and the milestone title when there is one."""
    pr = payload.get("pull_request") if isinstance(payload, dict) else None
    if not isinstance(pr, dict):
        return ["NOT MEASURABLE: the event payload carries no pull_request object"], None
    reasons: list[str] = []
    title = None
    if "milestone" not in pr:
        reasons.append("(a) NOT MEASURABLE: the payload's pull request has no milestone field")
    else:
        milestone = pr["milestone"]
        if milestone is None:
            reasons.append("(a) the pull request carries no milestone")
        elif (isinstance(milestone, dict) and isinstance(milestone.get("title"), str)
              and milestone["title"].strip()):
            title = milestone["title"]
        else:
            reasons.append("(a) NOT MEASURABLE: the milestone is not an object with a title")
    if "body" not in pr:
        reasons.append("(b) NOT MEASURABLE: the payload's pull request has no body field")
        reasons.append("(c) NOT MEASURABLE: the payload's pull request has no body field")
        return reasons, title
    # GitHub sends null for an empty description; an empty description has no footer.
    body = "" if pr["body"] is None else pr["body"]
    if not isinstance(body, str):
        reasons.append("(b) NOT MEASURABLE: the description is not text")
        reasons.append("(c) NOT MEASURABLE: the description is not text")
        return reasons, title
    if not ends_with_footer(body):
        reasons.append("(b) the description does not end with exactly the two lines of the house footer")
    try:
        reasons += [f"(c) the description carries {name}" for name in attribution_findings(body)]
    except NotMeasurable as exc:
        reasons.append(f"(c) NOT MEASURABLE: {exc}, so what renders as a link cannot be read")
    return reasons, title


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--event", required=True, type=pathlib.Path,
                        help="the event payload of the run, $GITHUB_EVENT_PATH")
    args = parser.parse_args(argv)
    try:
        payload = json.loads(args.event.read_bytes())
    except (OSError, ValueError) as exc:
        reasons, title = [f"NOT MEASURABLE: the event payload cannot be read ({type(exc).__name__})"], None
    else:
        reasons, title = judge(payload)
    print("pr-form: RED" if reasons else "pr-form: green")
    for reason in reasons:
        print(f"  {reason}")
    if title is not None:
        print(f"  milestone {title!r}")
    return 1 if reasons else 0


if __name__ == "__main__":
    sys.exit(main())
