#!/usr/bin/env python3
"""A pull request carries a milestone, and its description ends with the house footer.

Owner decision 2026-09-28: every pull request in this repository carries a milestone from the moment
it opens. Its description ends with exactly the two lines of the house footer, and it carries no tool
attribution, no session link and neither of the two retired closing sentences. Three rules:

  (a) the pull request has a milestone;
  (b) the description ends with exactly the two footer lines, separated by one empty line;
  (c) the description carries no tool attribution, no session link and no retired sentence.

WHAT IS READ. The event payload the runner writes for this run, `$GITHUB_EVENT_PATH`: the fields
`pull_request.milestone` and `pull_request.body`. No API call, no token. Its own workflow,
`.github/workflows/pr-form.yml`, runs this script and starts a run on `edited`, `milestoned` and
`demilestoned`, so a changed description or milestone is judged by a run that reads the new state;
ci.yml does not run it and does not start on those events.

WHAT (b) ACCEPTS. The two lines byte for byte, with one empty line between them, at the end of the
text or after a line break. A line break is LF or CRLF, because a description saved from the browser
carries CRLF; trailing line breaks after the footer are not text. Anything else after the footer, a
space included, is text after the footer.

WHAT (c) READS. The description is folded before the search: HTML character references resolved,
NFKC, format characters such as a zero-width space removed, case folded, whitespace runs collapsed,
and for the sentences the Markdown emphasis and escape marks dropped. A retired sentence broken over
two lines, in italics or in capitals is the same sentence. The rules name the FORM, not a list of
tools: an attribution is "Generated with" or "Generated by" followed by a Markdown link, and a session
link is an address whose path has a segment `session` or `sessions` followed by `_`, `-` or `/`.

LIMITS, said here. An attribution in another form, such as a tool named in plain prose without a
link, is not caught by (c); at the end of a description (b) still refuses it, because nothing may
follow the footer. A re-run of a job reads the payload of its original event and so judges the
description as it stood then; a new event starts a run with a new payload.

WHAT IS PRINTED. Never a byte of the description. The runner reads workflow commands from stdout,
and a description is text anyone who can open a pull request writes. The output names the rules
that failed, in fixed words, and the milestone title through repr on one line.

Exit: 0 green · 1 RED, with the reasons. The contract of the release-scope title gate: an input
this gate cannot read is RED and says NOT MEASURABLE, never a pass.
"""
from __future__ import annotations

import argparse
import html
import json
import pathlib
import re
import sys
import unicodedata

#: The house footer, the two lines in order. Between them one empty line, after them nothing.
FOOTER = ("Written by an AI session of b7n0de under owner review.", "Measurement, not certification.")
_FOOTER_TEXT = FOOTER[0] + "\n\n" + FOOTER[1]

#: The two retired closing sentences, by the part that names each of them. Searched in the folded
#: text, so a line break, emphasis or capitals inside the sentence do not hide it.
_RETIRED = (
    ("the retired closing sentence of the operating agent",
     re.compile(r"written by the operating agent under a standing owner authori[sz]ation")),
    ("the retired closing sentence of human oversight",
     re.compile(r"reviewed and submitted under human oversight")),
)

#: "Generated with" or "Generated by", followed by a Markdown link: the form tools append.
_ATTRIBUTION = re.compile(r"generated (?:with|by) \[[^\]]+\]\(")

#: An address whose path carries a segment `session` or `sessions` followed by `_`, `-` or `/`,
#: with or without a scheme.
_SESSION_LINK = re.compile(
    r"(?:[a-z][a-z0-9+.-]*://)?[a-z0-9-]+(?:\.[a-z0-9-]+)+(?::[0-9]+)?/(?:[^\s/()\[\]<>]+/)*sessions?[_/-]")


def _folded(text: str) -> str:
    text = unicodedata.normalize("NFKC", html.unescape(text))
    text = "".join(c for c in text if unicodedata.category(c) != "Cf")
    return text.casefold()


def _as_prose(folded: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[*_`~\\]", "", folded))


def _as_links(folded: str) -> str:
    return re.sub(r"\s+", " ", folded.replace("\\", ""))


def ends_with_footer(body: str) -> bool:
    """(b): the footer lines, exactly, as the last text."""
    text = body.replace("\r\n", "\n").rstrip("\n")
    return text == _FOOTER_TEXT or text.endswith("\n" + _FOOTER_TEXT)


def attribution_findings(body: str) -> list[str]:
    """(c): the names of every form found, in fixed words."""
    folded = _folded(body)
    prose = _as_prose(folded)
    found = [name for name, pattern in _RETIRED if pattern.search(prose)]
    if _ATTRIBUTION.search(prose):
        found.append("a tool attribution")
    if _SESSION_LINK.search(_as_links(folded)):
        found.append("a session link")
    return found


def judge(payload: object) -> tuple[list[str], str | None]:
    """The reasons for RED, empty when green, and the milestone title when there is one."""
    pr = payload.get("pull_request") if isinstance(payload, dict) else None
    if not isinstance(pr, dict):
        return ["NOT MEASURABLE: the event payload carries no pull_request object"], None
    reasons: list[str] = []
    title = None
    if "milestone" not in pr:
        reasons.append("(a) NOT MEASURABLE: the payload's pull request has no milestone field")
    else:
        milestone = pr["milestone"]
        if milestone is None:
            reasons.append("(a) the pull request carries no milestone")
        elif (isinstance(milestone, dict) and isinstance(milestone.get("title"), str)
              and milestone["title"].strip()):
            title = milestone["title"]
        else:
            reasons.append("(a) NOT MEASURABLE: the milestone is not an object with a title")
    if "body" not in pr:
        reasons.append("(b) NOT MEASURABLE: the payload's pull request has no body field")
        reasons.append("(c) NOT MEASURABLE: the payload's pull request has no body field")
        return reasons, title
    # GitHub sends null for an empty description; an empty description has no footer.
    body = "" if pr["body"] is None else pr["body"]
    if not isinstance(body, str):
        reasons.append("(b) NOT MEASURABLE: the description is not text")
        reasons.append("(c) NOT MEASURABLE: the description is not text")
        return reasons, title
    if not ends_with_footer(body):
        reasons.append("(b) the description does not end with exactly the two lines of the house footer")
    for name in attribution_findings(body):
        reasons.append(f"(c) the description carries {name}")
    return reasons, title


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--event", required=True, type=pathlib.Path,
                        help="the event payload of the run, $GITHUB_EVENT_PATH")
    args = parser.parse_args(argv)
    try:
        payload = json.loads(args.event.read_bytes())
    except (OSError, ValueError) as exc:
        reasons, title = [f"NOT MEASURABLE: the event payload cannot be read ({type(exc).__name__})"], None
    else:
        reasons, title = judge(payload)
    print("pr-form: RED" if reasons else "pr-form: green")
    for reason in reasons:
        print(f"  {reason}")
    if title is not None:
        print(f"  milestone {title!r}")
    return 1 if reasons else 0


if __name__ == "__main__":
    sys.exit(main())
